### ISSUE TITLE
Came up in our server console

### ISSUE THREAD

**Issue by ModernGamingWorld** [starforcraft/Botany-Pots-Tiers#1]
[12.09 18:03:23] [Server] [Worker-Main-12/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file botanypotstiers:elite_light_gray_botany_pot from botanypotstiers:recipes/elite_light_gray_botany_pot.json
[12.09 18:03:23] [Server] com.google.gson.JsonParseExceptioncom.google.gson.stream.MalformedJsonException: Expected name at line 15 column 6 path $.key.P
[12.09 18:03:23] [Server] 	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading}
[12.09 18:03:23] [Server] 	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading}
[12.09 18:03:23] [Server] 	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
[12.09 18:03:23] [Server] 	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
[12.09 18:03:23] [Server] 	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
[12.09 18:03:23] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?] {}
[12.09 18:03:23] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?] {}
[12.09 18:03:23] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
[12.09 18:03:23] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
[12.09 18:03:23] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {re:computing_frames}
[12.09 18:03:23] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {re:computing_frames}
[12.09 18:03:23] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
[12.09 18:03:23] [Server] Caused bycom.google.gson.stream.MalformedJsonException: Expected name at line 15 column 6 path $.key.P
[12.09 18:03:23] [Server] 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[12.09 18:03:23] [Server] 	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading}
[12.09 18:03:23] [Server] 	... more
[12.09 18:03:27] [Server] [Worker-Main-12/INFO] [KubeJS Server/]: [blocks] Found 1749 tags, added 1125 objects, removed 48 objects

**Comment by starforcraft** [comment]
Oh fuck i didnt saw this issue, sorry! I will fix it today

**Comment by starforcraft** [comment]
Hmm weird I think I fixed this in 1.11
