### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rogenar** [starforcraft/Botany-Pots-Tiers#21]
Versiyon BotanyPotsTiers-Fabric-1.20.1-6.0.0
![ss3](https://github.com/starforcraft/Botany-Pots-Tiers/assets/122460325/b3cdfa81-2158-41de-92aa-9509f5275b8f)
[latest.log](https://github.com/starforcraft/Botany-Pots-Tiers/files/12183533/latest.log)
I get an error like this when starting the world

**Comment by starforcraft** [comment]
This issue is not caused by Botany Pots Tiers. The log says that the Item Alchemy mod is the problem.

```
at ml.pkom.itemalchemy.ItemAlchemyClient.lambda$init$2(ItemAlchemyClient.java:44) ~[itemalchemy-0.7.1.jar:?]
	at ml.pkom.mcpitanlibarch.api.network.ClientNetworking.lambda$registerReceiver$0(ClientNetworking.java:17) ~[mcpitanlibarch-1.7.5-1.20.1-fabric.jar:?]
```

**Comment by Rogenar** [comment]
So how to fix this problem?

**Comment by Rogenar** [comment]
@starforcraft  So how to fix this problem?

**Comment by starforcraft** [comment]
Delete the mod or report it to them
