### ISSUE TITLE
Failed to load data for block entity

### ISSUE THREAD

**Issue by Niwood01** [starforcraft/Botany-Pots-Tiers#7]
Minecraft version: 1.19.2
Forge version: 43.1.38
Bookshelf version: Bookshelf-Forge-1.19.2-16.1.6 
BotanyPot version: BotanyPots-Forge-1.19.2-9.0.7
API: Forge
Version of the mod: BotanyPotsTiers-Forge-1.19.2-3.0.1.0

I'm playing on my local server. 

When i place a botany pot and i plant vanilla crop or modded crop and i go in nether or in the end (to make the chunk unloading) and i come back, everything I put in the botany pot disappears, i have tried to force load the chunk (with ftb chunk) and it's make the chunk dont load

The error in the console:

`[16Oct2022 12:54:09.539] [Server thread/ERROR] [net.minecraft.world.level.block.entity.BlockEntity/]: Failed to load data for block entity botanypotstiers:botany_pot
java.lang.NullPointerException: Cannot invoke "com.ultramega.botanypotstiers.PotTiers.getSpeed()" because the return value of "com.ultramega.botanypotstiers.block.TieredBlockEntityBotanyPot.getTier()" is null
	at com.ultramega.botanypotstiers.block.inv.TieredBotanyPotContainer.m_6596_(TieredBotanyPotContainer.java:78) ~[BotanyPotsTiers-Forge-1.19.2-3.0.0.jar%23136!/:3.0.0]
	at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainer.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.darkhax.bookshelf.api.util.IInventoryHelper.fill(IInventoryHelper.java:177) ~[Bookshelf-Forge-1.19.2-16.1.6.jar%23134!/:16.1.6]
	at net.darkhax.bookshelf.api.block.entity.InventoryBlockEntity.readInventory(InventoryBlockEntity.java:92) ~[Bookshelf-Forge-1.19.2-16.1.6.jar%23134!/:16.1.6]
	at net.darkhax.bookshelf.api.block.entity.InventoryBlockEntity.m_142466_(InventoryBlockEntity.java:128) ~[Bookshelf-Forge-1.19.2-16.1.6.jar%23134!/:16.1.6]
	at com.ultramega.botanypotstiers.block.TieredBlockEntityBotanyPot.m_142466_(TieredBlockEntityBotanyPot.java:266) ~[BotanyPotsTiers-Forge-1.19.2-3.0.0.jar%23136!/:3.0.0]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155246_(BlockEntity.java:122) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155241_(BlockEntity.java:120) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:422) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:429) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:691) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-5.0.28.jar%2375!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%2375!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-5.0.28.jar%2375!/:?]
	at net.minecraft.server.level.ChunkMap.m_214851_(ChunkMap.java:675) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23362!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/4030675
